@: src/atPrint.c File Reference
atPrint.c File Reference
The implementation of all functions declared in atPrint.h.
#include "atPrint.h"
#include <string.h>
Functions
bool isWithinBounds (AtScreen *atScreen, int x, int y, int xMargin, int yMargin)
Checks if the supplied coordinates, plus any additional margins, are within bounds of atScreen's buffer.
bool placeChar (AtScreen *atScreen, char c, int x, int y)
Places c at the x and y coordinates supplied.
bool placeDouble (AtScreen *atScreen, double d, int precision, int x, int y)
Places d at the x and y coordinates supplied.
bool placeInt (AtScreen *atScreen, int i, int x, int y)
Places i at the x and y coordinates supplied.
bool placeString (AtScreen *atScreen, char *s, int x, int y)
Places s at the x and y coordinates supplied.
Detailed Description
The implementation of all functions declared in atPrint.h.
Author
Frank Rodriguez
Date
6 August 2017
Definition in file atPrint.c.
Function Documentation
isWithinBounds()
bool isWithinBounds (AtScreen * atScreen, int x, int y, int xMargin, int yMargin)
Checks if the supplied coordinates, plus any additional margins, are within bounds of atScreen's buffer.
Returns
Returns true if the coordinates fit, false otherwise.
Definition at line 12 of file atPrint.c.
References AtScreen::height, and AtScreen::width.
Referenced by placeChar(), and placeString().
placeChar()
bool placeChar (AtScreen * atScreen, char c, int x, int y)
Places c at the x and y coordinates supplied.
Returns
Returns true if there was no error, or false if the supplied coordinates were out of bounds.
Definition at line 19 of file atPrint.c.
References AtScreen::buffer, AtScreen::height, isWithinBounds(), and AtScreen::width.
placeDouble()
bool placeDouble (AtScreen * atScreen, double d, int precision, int x, int y)
Places d at the x and y coordinates supplied.
Truncates d to the number of decimals dictated by precision.
Returns
Returns true if there was no error, or false if the supplied coordinates were out of bounds.
Definition at line 32 of file atPrint.c.
placeInt()
bool placeInt (AtScreen * atScreen, int i, int x, int y)
Places i at the x and y coordinates supplied.
Returns
Returns true if there was no error, or false if the supplied coordinates were out of bounds.
Definition at line 37 of file atPrint.c.
placeString()
bool placeString (AtScreen * atScreen, char * s, int x, int y)
Places s at the x and y coordinates supplied.
Returns
Returns true if there was no error, or false if the supplied coordinates were out of bounds.
Definition at line 42 of file atPrint.c.
References AtScreen::buffer, and isWithinBounds().